import type { FrameStyleConfig } from '../types/frame'

export const FRAME_STYLES: FrameStyleConfig[] = [
  {
    id: 'natural-oak',
    name: 'Natural Oak',
    material: 'wood',
    outerThicknessRatio: 0.05,
    innerThicknessRatio: 0.055,
    woodColor: '#c9a06a',
    matColor: '#f7f3ea',
    glassTintColor: '#eaf2ff',
    bevelStrength: 0.9,
    glassOpacity: 0.05,
    highlightStrength: 0.35,
    shadowStrength: 0.9,
    grainOpacity: 0.1,
    physicalThicknessRatio: 0.018,
  },
  {
    id: 'walnut',
    name: 'Walnut',
    material: 'wood',
    outerThicknessRatio: 0.06,
    innerThicknessRatio: 0.05,
    woodColor: '#5c3d28',
    matColor: '#f0ece3',
    glassTintColor: '#eaf2ff',
    bevelStrength: 1,
    glassOpacity: 0.05,
    highlightStrength: 0.3,
    shadowStrength: 1,
    grainOpacity: 0.13,
    physicalThicknessRatio: 0.02,
  },
  {
    id: 'matte-black',
    name: 'Matte Black',
    material: 'painted',
    outerThicknessRatio: 0.032,
    innerThicknessRatio: 0,
    woodColor: '#1c1c1e',
    matColor: null,
    glassTintColor: '#dfe6ee',
    bevelStrength: 0.5,
    glassOpacity: 0.07,
    highlightStrength: 0.25,
    shadowStrength: 1.1,
    grainOpacity: 0,
    physicalThicknessRatio: 0.012,
  },
  {
    id: 'white',
    name: 'White',
    material: 'painted',
    outerThicknessRatio: 0.042,
    innerThicknessRatio: 0.075,
    woodColor: '#f6f5f1',
    matColor: '#ffffff',
    glassTintColor: '#eef3fb',
    bevelStrength: 0.55,
    glassOpacity: 0.05,
    highlightStrength: 0.3,
    shadowStrength: 0.8,
    grainOpacity: 0,
    physicalThicknessRatio: 0.014,
  },
  {
    id: 'dark-brown',
    name: 'Dark Brown',
    material: 'wood',
    outerThicknessRatio: 0.058,
    innerThicknessRatio: 0.045,
    woodColor: '#3b2418',
    matColor: '#e9e3d6',
    glassTintColor: '#e6edf7',
    bevelStrength: 0.95,
    glassOpacity: 0.05,
    highlightStrength: 0.3,
    shadowStrength: 1,
    grainOpacity: 0.12,
    physicalThicknessRatio: 0.02,
  },
  {
    id: 'gold',
    name: 'Gold',
    material: 'metal',
    outerThicknessRatio: 0.072,
    innerThicknessRatio: 0.04,
    woodColor: '#b8892b',
    matColor: '#f8f4e3',
    glassTintColor: '#fbf6e8',
    bevelStrength: 1.3,
    glassOpacity: 0.06,
    highlightStrength: 0.5,
    shadowStrength: 1.2,
    grainOpacity: 0,
    physicalThicknessRatio: 0.024,
  },
]

export const DEFAULT_FRAME_STYLE_ID = FRAME_STYLES[0].id

export function getFrameStyle(id: string): FrameStyleConfig {
  return FRAME_STYLES.find((style) => style.id === id) ?? FRAME_STYLES[0]
}
